name: Deploy static content to Pages

on:
  push:
    branches: ["dev"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build config.js from template
        run: |
          echo "Gerando config.js com variaveis de ambiente"
          node build.js
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          REGION: ${{ secrets.REGION }}
          DOMAIN: ${{ secrets.DOMAIN }}
          AUTHORITY: ${{ secrets.AUTHORITY }}
          API_BASE_URL: ${{ secrets.API_BASE_URL }}

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
